### ISSUE TITLE
PDF generation eats up heap space

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#813]
```
PDF Java app returned non zero response code for 15812973: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at java.desktop/sun.java2d.pipe.DrawImage.makeBufferedImage(DrawImage.java:348)
	at java.desktop/sun.java2d.pipe.DrawImage.renderImageXform(DrawImage.java:468)
	at java.desktop/sun.java2d.pipe.DrawImage.transformImage(DrawImage.java:264)
	at java.desktop/sun.java2d.pipe.DrawImage.scaleImage(DrawImage.java:124)
	at java.desktop/sun.java2d.pipe.DrawImage.scaleImage(DrawImage.java:1063)
	at java.desktop/sun.java2d.pipe.ValidatePipe.scaleImage(ValidatePipe.java:207)
	at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3376)
	at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3314)
	at edu.yale.library.jpegs2pdf.JpegPdfConcatImpl.resizeImage(JpegPdfConcatImpl.java:365)
	at edu.yale.library.jpegs2pdf.JpegPdfConcatImpl.drawImageOnPage(JpegPdfConcatImpl.java:347)
	at edu.yale.library.jpegs2pdf.JpegPdfConcatImpl.addJpegPageToDocument(JpegPdfConcatImpl.java:317)
	at edu.yale.library.jpegs2pdf.JpegPdfConcatImpl.addJpegPages(JpegPdfConcatImpl.java:89)
	at edu.yale.library.jpegs2pdf.JpegPdfConcatImpl.generatePdf(JpegPdfConcatImpl.java:77)
	at edu.yale.library.jpegs2pdf.processor.JsonToPdfProcessorImpl.generatePdf(JsonToPdfProcessorImpl.java:70)
	at edu.yale.library.jpegs2pdf.App.main(App.java:26)
```

**Comment by dl-maura** [comment]
OID 15812973

**Comment by martinlovell** [comment]
Oddly, this oid just has 2 pages.  The first one is wide, but not that big: width: 14384, height: 6897.

The failure occurred when it was resizing the image.  (I think that during the resize, since it's coming from TIFF, it has to resample to change color space in some cases when the image has ICC.)

Tested locally by adding that oid, and didn't get any notifications.

Also tested generating from management shell without issues:

```
cam sh management
rails c
File.write("15812973.json", ParentObject.where(oid:15812973).first.pdf_generator_json)
exit
java -jar jpegs2pdf-1.0.jar 15812973.json 15812973.pdf
```
The resulting PDF seemed fine.

**Comment by martinlovell** [comment]
Tried running java app and limiting heap space and could cause out of memory errors.  Not exactly in the same place in code, but when reading the TIFF file.

Limiting it to 340m for this particular PDF worked consistently, but limiting to 330m caused out of memory errors:
```
app@a9b878c29f2e:~/webapp$ java -Xmx330m -jar jpegs2pdf-1.0.jar 15812973.json 15812973.pdf
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferByte.<init>(DataBufferByte.java:92)
	at java.desktop/java.awt.image.ComponentSampleModel.createDataBuffer(ComponentSampleModel.java:439)
	at java.desktop/java.awt.image.Raster.createWritableRaster(Raster.java:1005)
	at java.desktop/javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1074)
	at com.twelvemonkeys.imageio.ImageReaderBase.getDestination(ImageReaderBase.java:318)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:915)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1363)
	at edu.yale.library.jpegs2pdf.JpegPdfConcatImpl.drawImageOnPage(JpegPdfConcatImpl.java:326)
	at edu.yale.library.jpegs2pdf.JpegPdfConcatImpl.addJpegPageToDocument(JpegPdfConcatImpl.java:317)
	at edu.yale.library.jpegs2pdf.JpegPdfConcatImpl.addJpegPages(JpegPdfConcatImpl.java:89)
	at edu.yale.library.jpegs2pdf.JpegPdfConcatImpl.generatePdf(JpegPdfConcatImpl.java:77)
	at edu.yale.library.jpegs2pdf.processor.JsonToPdfProcessorImpl.generatePdf(JsonToPdfProcessorImpl.java:70)
	at edu.yale.library.jpegs2pdf.App.main(App.java:26)
app@a9b878c29f2e:~/webapp$ java -Xmx340m -jar jpegs2pdf-1.0.jar 15812973.json 15812973.pdf
Generated: 2 in 48090 at 24045
```

We can look at ways of reducing the memory usage.  One way would be to make sure we are taking advantage of the PTIFF by using the one closest to our destination size.  We will still need enough memory to load the entire PTIFF into memory.  For this oid, one image is 40.8 MB, the other is 18.1 MB.

Q: How much heap space can the java app use?

**Comment by martinlovell** [comment]
Information:
- Each PDF generation is an independent process, so once it exits, the memory is freed by the OS.  It's not an issue of the PDF generation holding onto memory between jobs, it's the number of jobs running concurrently.
- Each PDF generation job will need heap space to read the PTIFF from S3 and to generate the PDF.  More memory is required for items with more children and for items with large PTIFFs.
- While we might be able to save some processing time by choosing a smaller image from the PTIFF, it's not likely to affect memory requirements, since it usually runs out of memory reading the PTIFF before it tries to do anything with it.

Other tests:
- I'd like to test a PDF for an item with 1000+ images to see how much memory is required and if it's successful.  Looking for an oid to use that has PTIFFs on S3 in the development bucket.

Options for moving forward:
- We could reduce the memory requirements by either getting a JPEG from the IIIF server (easy), or extract an image from the PTIFF without loading the whole file into memory (hard).  It may be possible to write PTIFF to disk and pull out the correct image by seeking on the disk, so that the whole PTIFF doesn't need to be loaded into memory.  (It may be possible to do this while streaming from S3 (depending on the file structure for PTIFFs) or using S3 API to seek if that's possible.)
- We can reduce the number of concurrent PDF generation jobs on a container to prevent these errors.

**Comment by dl-maura** [comment]
I provided Martin was a 1000+ example

**Comment by maxkadel** [comment]
- Thought
  - The PTIFF generation script already generates multiple sizes of derivatives, smashes them together, then throws away the derivatives. Perhaps we could save *one* of those derivatives, or save it as a jpeg, to S3, and then the PDF generation could use those derivatives to generate / re-generate PDFs.

**Comment by dl-maura** [comment]
Explore extracting the correctly sized tif from the ptiff file

**Comment by martinlovell** [comment]
The large PDF that @dl-maura suggested trying was generated successfully:
https://drive.google.com/file/d/1LPAVju2l6uWnvduBHwdWxoevfqAf-Tc6/view?usp=sharing

It's for this item: https://collections-test.library.yale.edu/catalog/2041002
Page count: 1318
PDF file size: 400M

Memory on my local management container (when the Java app is **NOT** running):
```
free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        1.8G        1.5G         28M        532M        1.8G
Swap:          1.0G         30M        993M
```

(Some pages have small images because they have a aspect ratio > 1 and the page has aspect ratio< 1....which may have made it easier.)

Steps to generate:
```
cam sh management
rails c
ENV['S3_SOURCE_BUCKET_NAME']='yul-dc-image-samples'
p = ParentObject.where(oid:2041002).first
File.write("#{p.oid}.json", p.pdf_generator_json)
exit
java -jar jpegs2pdf-1.0.jar 2041002.json 2041002.pdf
```
Wait a long time.....

**Comment by martinlovell** [comment]
Added ability to specify a preprocessing command in json sent to PDF app to run on each image before being used.

Tested with `"imageProcessingCommand":"vips jpegsave %s %s"`

**Comment by martinlovell** [comment]
We came up with a preprocessing command that seems to work reasonably:
`convert -resize 2000x2000 %s[0] %s`  (Convert to image with max size of 2000x2000 keeping aspect ratio.)

It doesn't search for the optimal size in the ptiff, but it seems to work fine with the largest tiff.

Regenerated 2041002 using this code and the resulting PDF is also smaller (bonus) at 350MB vs 400MB.

https://github.com/yalelibrary/yul-dc-management/pull/399
https://github.com/yalelibrary/yul-dc-pdf-gen/pull/4

**Comment by martinlovell** [comment]
I updated the JAR to call system.exit().
It seemed like sometimes the java app would hang after writing the PDF, so this may help.
Also updated ruby code to more safely check if the app exited correctly.

See: 
https://github.com/yalelibrary/yul-dc-pdf-gen/pull/5
https://github.com/yalelibrary/yul-dc-management/pull/403
