### ISSUE TITLE
Intermittent test failure on Blacklight

### ISSUE THREAD

**Issue by maxkadel** [yalelibrary/YUL-DC#924]
Intermittent Date Slider spec failure - fails intermittently in local development as well.

https://app.circleci.com/pipelines/github/yalelibrary/yul-dc-blacklight/1593/workflows/6c673569-9db4-4166-988b-b6f3170c91b8/jobs/3832

```
Failures:

  1) Blacklight Range Limit is able to search with the slider
     Failure/Error: expect(page.text).to match(/12\d\d to 16\d\d/)
     
       expected "DATE CREATED\n1100 to 1607\n✖\n[remove]\n5\n1100\n1200\n1300\n1400\n1500\n1600\nCurrent results range from to\nDate Created range begin\nDate Created range end\nView larger »" to match /12\d\d to 16\d\d/
       Diff:
       @@ -1,2 +1,16 @@
       -/12\d\d to 16\d\d/
       +DATE CREATED
       +1100 to 1607
       +✖
       +[remove]
       +5
       +1100
       +1200
       +1300
       +1400
       +1500
       +1600
       +Current results range from to
       +Date Created range begin
       +Date Created range end
       +View larger »
       
     
     [Screenshot]: /home/app/webapp/tmp/screenshots/failures_r_spec_example_groups_blacklight_range_limit_is_able_to_search_with_the_slider_449.png

     
     # ./spec/system/date_slider_spec.rb:126:in `block (3 levels) in <top (required)>'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/session.rb:345:in `within'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/dsl.rb:58:in `block (2 levels) in <module:DSL>'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/capybara-3.33.0/lib/capybara/rspec/matcher_proxies.rb:15:in `within'
     # ./spec/system/date_slider_spec.rb:125:in `block (2 levels) in <top (required)>'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/webmock-3.9.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 1 minute 40.27 seconds (files took 7.01 seconds to load)
270 examples, 1 failure, 6 pending

Failed examples:

rspec ./spec/system/date_slider_spec.rb:109 # Blacklight Range Limit is able to search with the slider
```

**Comment by maxkadel** [comment]
I'm continuing to see this failure, which means we periodically have to re-run CI

**Comment by maxkadel** [comment]
And still - https://app.circleci.com/pipelines/github/yalelibrary/yul-dc-blacklight/1727/workflows/027f321d-5281-444c-b6c3-877e5d734fa4/jobs/4195
